// ============================================================
// THE DIET HUB — OFFICIAL 53 ITEMS MENU CATALOGUE
// Strictly contains only the 53 items from the menu board
// ============================================================

export type Diet = "veg" | "vegan" | "egg" | "nonveg";

export type CatKey =
  | "all"
  | "daily-meals"
  | "combo-meals"
  | "chicken-meals"
  | "special-meals"
  | "diet-meals"
  | "salads"
  | "roti-items"
  | "snacks"
  | "soups"
  | "smoothies"
  | "fresh-juices"
  | "milkshakes";

export const CATEGORIES: { k: CatKey; l: string; te: string }[] = [
  { k: "all",           l: "All Items",                  te: "అన్నీ" },
  { k: "daily-meals",   l: "Daily Meals",                te: "డైలీ మీల్స్" },
  { k: "combo-meals",   l: "Combo Meals",                te: "కాంబో మీల్స్" },
  { k: "chicken-meals", l: "Chicken Meals",              te: "చికెన్ మీల్స్" },
  { k: "special-meals", l: "Special Meals",              te: "స్పెషల్ మీల్స్" },
  { k: "diet-meals",    l: "Diet Meals (Weight Loss)",   te: "డైట్ మీల్స్ (వెయిట్ లాస్)" },
  { k: "salads",        l: "Salads",                     te: "సలాడ్స్" },
  { k: "roti-items",    l: "Roti Items",                 te: "రోటీ ఐటెమ్స్" },
  { k: "snacks",        l: "Snacks",                     te: "స్నాక్స్" },
  { k: "soups",         l: "Soups",                      te: "సూప్స్" },
  { k: "smoothies",     l: "Healthy Smoothies",          te: "హెల్తీ స్మూతీస్" },
  { k: "fresh-juices",  l: "Fresh Juices",               te: "ఫ్రెష్ జ్యూసెస్" },
  { k: "milkshakes",    l: "Milkshakes",                 te: "మిల్క్‌షేక్స్" },
];

export type Nutrition = {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fibre: number;
  sugar: number;
  sodium: number;    // mg
  calcium: number;   // mg
  iron: number;      // mg
  potassium: number; // mg
  vitC: number;      // mg
};

export type Product = {
  id: string;
  name: string;
  nameTe: string;
  desc: string;
  cats: CatKey[];
  diet: Diet;
  price: number;
  serving: string;
  prepTime: string;
  bestTime?: string;      // UI లో వాడుతున్న ఫీల్డ్
  enquiryOnly?: boolean;  // UI లో వాడుతున్న ఫీల్డ్
  kcalBand: string;
  img: string;
  ingredients: string[];
  ingredientsTe: string;
  allergens: string[];
  n: Nutrition;
  bestFor: string[];
  avoidIf: string[];
  benefits: string[];
  popular?: boolean;
};
export const PRODUCTS: Product[] = [
  // ======================= 1. DAILY MEALS =======================
  {
    id: "ragi-mudda",
    name: "Ragi Mudda (Ragi Sangati)",
    nameTe: "రాగి ముద్ద (రాగి సంగటి)",
    desc: "Traditional Rayalaseema steamed finger-millet ball. Rich in calcium, iron, and slow-digesting complex carbs.",
    cats: ["daily-meals", "diet-meals"],
    diet: "vegan",
    price: 50,
    serving: "1 Ball (~180g)",
    prepTime: "10 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "160–180 kcal",
    img: "https://i.pinimg.com/1200x/24/03/a3/2403a3daaae9970c8fdfb9d86208d6da.jpg",
    ingredients: ["Finger Millet (Ragi) Flour", "Water", "Rock Salt"],
    ingredientsTe: "రాగి పిండి, నీరు, రాతి ఉప్పు",
    allergens: [],
    n: {
      calories: 170,
      protein: 5,
      carbs: 34,
      fat: 1.5,
      fibre: 4.5,
      sugar: 0.5,
      sodium: 95,
      calcium: 210,
      iron: 2.8,
      potassium: 240,
      vitC: 0
    },
    bestFor: ["Diabetes Management", "Weight Loss", "Bone Health", "Sustained Energy"],
    avoidIf: [],
    benefits: [
      "Highest calcium content among all millets",
      "Low glycemic index prevents insulin spikes",
      "Naturally gluten-free & easy on the gut",
      "Keeps you satiated for 4–5 hours"
    ],
    popular: true,
  },

  // ======================= SIGNATURE COMBO MEALS =======================
  {
    id: "brown-rice-chicken-curry-raita",
    name: "Brown Rice with Chicken Curry & Raita",
    nameTe: "బ్రౌన్ రైస్ + చికెన్ కర్రీ + రైతా",
    desc: "Nutritious brown rice served with authentic homestyle chicken curry and cooling cucumber-tomato curd raita.",
    cats: ["combo-meals", "chicken-meals", "daily-meals"],
    diet: "nonveg",
    price: 189,
    serving: "1 Meal Box (450g)",
    prepTime: "15 min",
    bestTime: "Lunch",
    kcalBand: "440–470 kcal",
    img: "https://i.ibb.co/vCzgqWVg/Gemini-Generated-Image-1f9sd31f9sd31f9s.png",
    ingredients: ["Brown rice 120g", "Homestyle chicken curry", "Cucumber-tomato raita", "Fresh salad"],
    ingredientsTe: "బ్రౌన్ రైస్, నాటు చికెన్ కర్రీ, దోసకాయ-టమాటా రైతా, సలాడ్",
    allergens: ["dairy"],
    n: { calories: 450, protein: 27, carbs: 54, fat: 16, fibre: 5, sugar: 5, sodium: 540, calcium: 90, iron: 2.6, potassium: 460, vitC: 10 },
    bestFor: ["High Protein Lunch", "Weight Loss", "Balanced Nutrition"],
    avoidIf: ["Lactose Intolerance (Raita can be skipped)"],
    benefits: [
      "Whole-grain brown rice ensures slow glucose release",
      "Cooling raita perfectly balances Andhra spices",
      "Lean protein supports muscle maintenance"
    ],
    popular: true,
  },
  {
    id: "veg-bhavna-rice-chicken-keema-balls",
    name: "Vegetable Bhavana Rice with Chicken Keema Balls",
    nameTe: "వెజిటబుల్ భావనా రైస్ + చికెన్ కీమా బాల్స్",
    desc: "Nutrient-packed Bhavana millet rice tossed with farm veggies, served with spiced minced chicken keema balls.",
    cats: ["combo-meals", "chicken-meals"],
    diet: "nonveg",
    price: 199,
    serving: "1 Rice Box + Keema Balls (450g)",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "430–460 kcal",
    img: "https://res.cloudinary.com/tru9hwfl/image/upload/v1787730336/veg_bhavana_keema_rice_zibecu.jpg",
    ingredients: ["Bhavana millet rice", "Minced chicken keema balls", "Carrot & Beans", "Fresh coriander"],
    ingredientsTe: "భావనా రైస్, చికెన్ కీమా బాల్స్, క్యారెట్ & బీన్స్, కొత్తిమీర",
    allergens: [],
    n: { calories: 440, protein: 27, carbs: 50, fat: 15, fibre: 4, sugar: 3, sodium: 500, calcium: 35, iron: 2.6, potassium: 430, vitC: 12 },
    bestFor: ["Active Lifestyles", "High Protein", "Fitness Enthusiasts"],
    avoidIf: [],
    benefits: [
      "Vegetables cooked right into the millet rice base",
      "Lean chicken keema balls provide rapid protein absorption",
      "Single-box wholesome complete meal"
    ],
  },
  {
    id: "brown-rice-fish-fry-chinna-masala",
    name: "Brown Rice with Fish Fry, Chinna Masala & Gravy",
    nameTe: "బ్రౌన్ రైస్ + ఫిష్ ఫ్రై + చిన్న మసాలా గ్రేవీ",
    desc: "Steamed brown rice paired with tawa-crisped fish fillet and traditional Andhra Chinna Masala gravy.",
    cats: ["combo-meals", "special-meals"],
    diet: "nonveg",
    price: 209,
    serving: "1 Rice Box + Fish Fry + Gravy",
    prepTime: "15 min",
    bestTime: "Lunch",
    kcalBand: "420–450 kcal",
    img: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    ingredients: ["Brown rice 120g", "Tawa fish fry", "Chinna masala gravy", "Lemon wedge"],
    ingredientsTe: "బ్రౌన్ రైస్, ఫిష్ ఫ్రై, చిన్న మసాలా గ్రేవీ, నిమ్మకాయ",
    allergens: ["seafood"],
    n: { calories: 430, protein: 25, carbs: 52, fat: 14, fibre: 5, sugar: 3, sodium: 510, calcium: 50, iron: 2.0, potassium: 440, vitC: 8 },
    bestFor: ["Traditional Taste", "Heart Health", "Coastal Non-Veg Lovers"],
    avoidIf: ["Fish Allergy"],
    benefits: [
      "Authentic coastal Andhra Chinna Masala blend",
      "Tawa grilled fish with low oil absorption",
      "Rich in trace minerals and omega-3"
    ],
  },
  {
    id: "red-rice-chicken-fry",
    name: "Red Rice with Chicken Fry",
    nameTe: "రెడ్ రైస్ + చికెన్ ఫ్రై",
    desc: "Antioxidant-rich organic red rice served with crisp tawa chicken fry and steamed garden greens.",
    cats: ["combo-meals", "chicken-meals"],
    diet: "nonveg",
    price: 189,
    serving: "1 Meal Box (430g)",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "420–450 kcal",
    img: "https://res.cloudinary.com/tru9hwfl/image/upload/v1787730275/ragi_chapthi_h0jybl.jpg",
    ingredients: ["Organic red rice", "Tawa chicken fry", "Steamed carrots & beans", "Onion rings"],
    ingredientsTe: "రెడ్ రైస్, చికెన్ ఫ్రై, ఉడికించిన కూరగాయలు, ఉల్లిపాయ",
    allergens: [],
    n: { calories: 430, protein: 28, carbs: 50, fat: 14, fibre: 5, sugar: 2, sodium: 500, calcium: 30, iron: 2.8, potassium: 420, vitC: 12 },
    bestFor: ["Antioxidant Intake", "Fibre & Digestion", "Muscle Building"],
    avoidIf: [],
    benefits: [
      "Red rice contains natural anthocyanin antioxidants",
      "Crispy exterior with tender, juicy lean chicken inside",
      "Zero refined flour or artificial food coloring"
    ],
  },
  {
    id: "bhavna-rice-mint-chicken-fry",
    name: "Bhavana Rice with Mint Chicken Fry",
    nameTe: "భావనా రైస్ + మింట్ చికెన్ ఫ్రై",
    desc: "Light Bhavana millet rice served with fresh pudina-marinated tawa chicken fry and crisp cucumber slices.",
    cats: ["combo-meals", "chicken-meals"],
    diet: "nonveg",
    price: 189,
    serving: "1 Meal Box (420g)",
    prepTime: "15 min",
    bestTime: "Post-Workout / Lunch",
    kcalBand: "410–440 kcal",
    img: "https://i.ibb.co/CKJDbtJY/Gemini-Generated-Image-vrgdvvvrgdvvvrgd.png",
    ingredients: ["Bhavana millet rice", "Mint marinated chicken", "Cucumber & lime salad"],
    ingredientsTe: "భావనా రైస్, పుదీనా చికెన్ ఫ్రై, దోసకాయ సలాడ్",
    allergens: [],
    n: { calories: 420, protein: 29, carbs: 45, fat: 14, fibre: 3, sugar: 2, sodium: 490, calcium: 28, iron: 2.3, potassium: 410, vitC: 9 },
    bestFor: ["Cooling Digestion", "Lean Protein", "Post-Workout Lunch"],
    avoidIf: [],
    benefits: [
      "Fresh mint marinade aids smooth gastric digestion",
      "High protein-to-calorie ratio",
      "Refreshing and light on the palate"
    ],
  },
  {
    id: "bhavna-rice-spicy-chicken",
    name: "Bhavana Rice with Spicy Chicken",
    nameTe: "భావనా రైస్ + స్పైసీ చికెన్",
    desc: "Bhavana millet rice accompanied by fiery Andhra-spiced chicken, cucumber cuts, and onion relish.",
    cats: ["combo-meals", "chicken-meals"],
    diet: "nonveg",
    price: 189,
    serving: "1 Meal Box (430g)",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "420–450 kcal",
    img: "https://i.ibb.co/k6stQvt3/Whats-App-Image-2026-08-08-at-5-35-10-AM.jpg",
    ingredients: ["Bhavana millet rice", "Fiery grilled chicken", "Cucumber cuts", "Onion salad"],
    ingredientsTe: "భావనా రైస్, స్పైసీ చికెన్, దోసకాయ ముక్కలు, ఉల్లి సలాడ్",
    allergens: [],
    n: { calories: 430, protein: 28, carbs: 46, fat: 15, fibre: 3, sugar: 2, sodium: 520, calcium: 30, iron: 2.5, potassium: 400, vitC: 8 },
    bestFor: ["Spicy Food Lovers", "Full Meal", "Protein Satiety"],
    avoidIf: ["Severe Gastric Acidity"],
    benefits: [
      "Bold Andhra spice profile without heavy oils",
      "Low glycemic millet grain foundation",
      "Keeps energy levels stable for hours"
    ],
    popular: true,
  },
  {
    id: "veg-meal",
    name: "Veg Meal",
    nameTe: "వెజ్ మీల్",
    desc: "Wholesome daily vegetarian balanced meal box with rice, dal, mixed veg curry, and curd.",
    cats: ["daily-meals"],
    diet: "veg",
    price: 140,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch",
    kcalBand: "450–480 kcal",
    img: "https://i.pinimg.com/736x/13/c6/b8/13c6b80d601de2fff27297afad524e7c.jpg",
    ingredients: ["Rice", "Toor Dal", "Mixed Veg Curry", "Curd", "Salad"],
    ingredientsTe: "రైస్, పప్పు, వెజిటబుల్ కర్రీ, పెరుగు, సలాడ్",
    allergens: ["dairy"],
    n: { calories: 460, protein: 14, carbs: 70, fat: 10, fibre: 8, sugar: 4, sodium: 420, calcium: 110, iron: 2.8, potassium: 520, vitC: 18 },
    bestFor: ["Everyday Lunch", "Balanced Diet"],
    avoidIf: [],
    benefits: ["Balanced macros", "Home-style cooking", "No preservatives"],
    popular: true,
  },
  {
    id: "non-veg-meal",
    name: "Non-Veg Meal",
    nameTe: "నాన్-వెజ్ మీల్",
    desc: "Complete daily meal box with rice, homestyle chicken curry, dal, and fresh salad.",
    cats: ["daily-meals"],
    diet: "nonveg",
    price: 170,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "500–550 kcal",
    img: "https://i.pinimg.com/1200x/83/5a/7a/835a7a7b3690d98b6e8088fc43ad8968.jpg",
    ingredients: ["Rice", "Chicken Curry", "Dal", "Salad", "Curd"],
    ingredientsTe: "రైస్, చికెన్ కర్రీ, పప్పు, సలాడ్, పెరుగు",
    allergens: ["dairy"],
    n: { calories: 520, protein: 26, carbs: 65, fat: 14, fibre: 6, sugar: 3, sodium: 520, calcium: 70, iron: 3.5, potassium: 560, vitC: 12 },
    bestFor: ["Daily Protein", "Full Lunch"],
    avoidIf: [],
    benefits: ["High protein", "Low oil homestyle curry", "Filling & energetic"],
    popular: true,
  },
  {
    id: "paneer-meal",
    name: "Paneer Meal",
    nameTe: "పనీర్ మీల్",
    desc: "Rich vegetarian protein meal with fresh paneer curry, rice, dal, and fresh salad.",
    cats: ["daily-meals"],
    diet: "veg",
    price: 160,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "480–520 kcal",
    img: "https://i.pinimg.com/736x/9c/ea/92/9cea927f3806f9e74b1c9ac5a3d5db35.jpg",
    ingredients: ["Rice", "Fresh Paneer Curry", "Dal", "Salad", "Curd"],
    ingredientsTe: "రైస్, పనీర్ కర్రీ, పప్పు, సలాడ్, పెరుగు",
    allergens: ["dairy"],
    n: { calories: 510, protein: 22, carbs: 64, fat: 16, fibre: 7, sugar: 4, sodium: 480, calcium: 340, iron: 2.6, potassium: 490, vitC: 14 },
    bestFor: ["Veg Protein", "Muscle Health"],
    avoidIf: ["Lactose Intolerance"],
    benefits: ["High calcium & protein", "Fresh low-fat paneer", "Sustained fullness"],
  },
  {
    id: "egg-meal",
    name: "Egg Meal",
    nameTe: "ఎగ్ మీల్",
    desc: "Nutritious daily meal box with boiled egg curry, rice, dal, and cooling salad.",
    cats: ["daily-meals"],
    diet: "egg",
    price: 150,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "460–490 kcal",
    img: "https://i.pinimg.com/1200x/b3/4e/72/b34e727e612fd0669515776f8ef0d2c6.jpg",
    ingredients: ["Rice", "2 Eggs Curry", "Dal", "Salad"],
    ingredientsTe: "రైస్, ఎగ్ కర్రీ (2 గుడ్లు), పప్పు, సలాడ్",
    allergens: ["egg"],
    n: { calories: 470, protein: 19, carbs: 62, fat: 13, fibre: 6, sugar: 3, sodium: 460, calcium: 80, iron: 3.1, potassium: 430, vitC: 10 },
    bestFor: ["Affordable Protein", "Daily Lunch"],
    avoidIf: ["Egg Allergy"],
    benefits: ["Complete protein amino acids", "Light and easy to digest", "Comfort food"],
  },
  {
    id: "fish-meal",
    name: "Fish Meal",
    nameTe: "ఫిష్ మీల్",
    desc: "Coastal-style tangy fish curry served with steamed rice, dal, and fresh cucumber slices.",
    cats: ["daily-meals"],
    diet: "nonveg",
    price: 190,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch",
    kcalBand: "440–470 kcal",
    img: "https://i.pinimg.com/736x/70/d1/7a/70d17a9a1059023c17efe2e4b70f3453.jpg",
    ingredients: ["Rice", "Fresh Fish Curry", "Dal", "Salad"],
    ingredientsTe: "రైస్, చేపల పులుసు, పప్పు, సలాడ్",
    allergens: ["seafood"],
    n: { calories: 450, protein: 24, carbs: 62, fat: 10, fibre: 5, sugar: 3, sodium: 490, calcium: 60, iron: 2.2, potassium: 510, vitC: 8 },
    bestFor: ["Heart Health", "Lean Protein"],
    avoidIf: ["Fish Allergy"],
    benefits: ["Omega-3 fatty acids", "Easily digestible lean fish", "Authentic tangy taste"],
  },
  {
    id: "prawns-meal",
    name: "Prawns Meal",
    nameTe: "ప్రాన్స్ మీల్",
    desc: "Spiced prawns masala curry served with rice, dal, and fresh crisp salad.",
    cats: ["daily-meals"],
    diet: "nonveg",
    price: 210,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "450–480 kcal",
    img: "https://i.pinimg.com/736x/35/ed/55/35ed55076cddd37eff4550e83f03fb35.jpg",
    ingredients: ["Rice", "Prawns Curry", "Dal", "Salad"],
    ingredientsTe: "రైస్, రొయ్యల కర్రీ, పప్పు, సలాడ్",
    allergens: ["seafood"],
    n: { calories: 460, protein: 25, carbs: 63, fat: 9, fibre: 5, sugar: 2, sodium: 530, calcium: 75, iron: 2.9, potassium: 480, vitC: 9 },
    bestFor: ["Seafood Lovers", "Lean Protein"],
    avoidIf: ["Seafood Allergy"],
    benefits: ["Low in fat & calories", "High in zinc and protein", "Delicate coastal flavour"],
  },

  // ======================= 2. CHICKEN MEALS =======================
  {
    id: "chicken-curry-meal",
    name: "Chicken Curry Meal",
    nameTe: "చికెన్ కర్రీ మీల్",
    desc: "Tender chicken pieces cooked in traditional spices served with steamed rice, dal, and salad.",
    cats: ["chicken-meals"],
    diet: "nonveg",
    price: 180,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "510–550 kcal",
    img: "https://i.pinimg.com/1200x/ee/13/67/ee13672c4b088a00a2f861bc8859c470.jpg",
    ingredients: ["Rice", "Chicken Curry", "Dal", "Salad"],
    ingredientsTe: "రైస్, చికెన్ కర్రీ, పప్పు, సలాడ్",
    allergens: [],
    n: { calories: 530, protein: 28, carbs: 64, fat: 15, fibre: 5, sugar: 3, sodium: 540, calcium: 65, iron: 3.4, potassium: 520, vitC: 11 },
    bestFor: ["Classic Non-Veg Lunch", "Protein Intake"],
    avoidIf: [],
    benefits: ["Rich authentic flavour", "High muscle-building protein", "Wholesome lunch"],
  },

  // ======================= 3. SPECIAL MEALS =======================
  {
    id: "mutton-meal",
    name: "Mutton Meal",
    nameTe: "మటన్ మీల్",
    desc: "Slow-cooked tender mutton curry served with steamed rice, dal, and fresh garden salad.",
    cats: ["special-meals"],
    diet: "nonveg",
    price: 240,
    serving: "1 Meal Box",
    prepTime: "20 min",
    bestTime: "Special Lunch",
    kcalBand: "560–610 kcal",
    img: "https://i.pinimg.com/1200x/a7/da/3b/a7da3b3c5d7cb9ad0401d42ee3db1cfb.jpg",
    ingredients: ["Rice", "Mutton Curry", "Dal", "Salad"],
    ingredientsTe: "రైస్, మటన్ కర్రీ, పప్పు, సలాడ్",
    allergens: [],
    n: { calories: 580, protein: 28, carbs: 62, fat: 22, fibre: 5, sugar: 2, sodium: 560, calcium: 60, iron: 4.8, potassium: 520, vitC: 6 },
    bestFor: ["Iron Levels", "Special Non-Veg Feast"],
    avoidIf: ["High Cholesterol"],
    benefits: ["Rich in bioavailable iron", "High satiety", "Authentic slow-cooked flavour"],
  },
  {
    id: "fish-curry-meal",
    name: "Fish Curry Meal",
    nameTe: "ఫిష్ కర్రీ మీల్",
    desc: "Traditional Andhra coastal style fish curry meal with steamed rice and fresh veggies.",
    cats: ["special-meals"],
    diet: "nonveg",
    price: 190,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch",
    kcalBand: "440–470 kcal",
    img: "https://i.pinimg.com/1200x/63/e3/96/63e3962210c99391662e76d23caa58aa.jpg",
    ingredients: ["Rice", "Fish Curry (Tangy)", "Dal", "Salad"],
    ingredientsTe: "రైస్, చేపల పులుసు, పప్పు, సలాడ్",
    allergens: ["seafood"],
    n: { calories: 450, protein: 24, carbs: 62, fat: 10, fibre: 5, sugar: 3, sodium: 490, calcium: 60, iron: 2.2, potassium: 510, vitC: 8 },
    bestFor: ["Heart Health", "Omega 3"],
    avoidIf: ["Fish Allergy"],
    benefits: ["Rich in healthy fatty acids", "Easily digestible", "Traditional recipe"],
  },
  {
    id: "prawns-curry-meal",
    name: "Prawns Curry Meal",
    nameTe: "ప్రాన్స్ కర్రీ మీల్",
    desc: "Aromatic prawns gravy curry with spices, served with steaming rice and salad.",
    cats: ["special-meals"],
    diet: "nonveg",
    price: 210,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "450–480 kcal",
    img: "https://i.pinimg.com/1200x/74/4c/3a/744c3a95ad1d1eaab77b41fc3b9cfb03.jpg",
    ingredients: ["Rice", "Prawns Masala Gravy", "Dal", "Salad"],
    ingredientsTe: "రైస్, రొయ్యల మసాలా కర్రీ, పప్పు, సలాడ్",
    allergens: ["seafood"],
    n: { calories: 460, protein: 25, carbs: 63, fat: 9, fibre: 5, sugar: 2, sodium: 530, calcium: 75, iron: 2.9, potassium: 480, vitC: 9 },
    bestFor: ["Seafood Protein", "Sunday Special"],
    avoidIf: ["Seafood Allergy"],
    benefits: ["Low fat & high protein", "Delicious Andhra masala", "Nutrient dense"],
  },
  {
    id: "biryani-meal",
    name: "Biryani Meal",
    nameTe: "బిర్యానీ మీల్",
    desc: "Low-oil aromatic dum biryani served with protein raita and fresh salad.",
    cats: ["special-meals"],
    diet: "nonveg",
    price: 199,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "520–560 kcal",
    img: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    ingredients: ["Basmati Rice", "Tender Chicken", "Spices", "Raita", "Salad"],
    ingredientsTe: "బాస్మతి రైస్, చికెన్ ముక్కలు, రైతా, సలాడ్",
    allergens: ["dairy"],
    n: { calories: 540, protein: 27, carbs: 68, fat: 14, fibre: 4, sugar: 3, sodium: 540, calcium: 80, iron: 3.1, potassium: 460, vitC: 6 },
    bestFor: ["Biryani Lovers", "Weekend Cheat Without Guilt"],
    avoidIf: [],
    benefits: ["Cooked in minimal cold-pressed oil", "Zero artificial colours", "Rich taste"],
    popular: true,
  },

  // ======================= 4. DIET MEALS (WEIGHT LOSS) =======================
  {
    id: "weight-loss-meal",
    name: "Weight Loss Meal",
    nameTe: "వెయిట్ లాస్ మీల్",
    desc: "Calorie-counted weight loss box with boiled pulses, mixed greens, fibre-rich millet, and lemon-herb dressing.",
    cats: ["diet-meals"],
    diet: "vegan",
    price: 160,
    serving: "1 Meal Box",
    prepTime: "12 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "300–340 kcal",
    img: "https://i.pinimg.com/736x/e1/05/76/e1057673573b615ca9b7e574f619a8bc.jpg",
    ingredients: ["Foxtail Millet", "Boiled Moong & Chana", "Steamed Veggies", "Salad"],
    ingredientsTe: "కొర్రలు, మొలకలు, ఉడికించిన కూరగాయలు, సలాడ్",
    allergens: [],
    n: { calories: 320, protein: 16, carbs: 46, fat: 5, fibre: 11, sugar: 3, sodium: 280, calcium: 85, iron: 3.6, potassium: 560, vitC: 28 },
    bestFor: ["Fat Loss", "Calorie Counting", "Detox"],
    avoidIf: [],
    benefits: ["11g dietary fibre", "Promotes fat burning", "Zero refined sugars or oils"],
    popular: true,
  },
  {
    id: "high-protein-meal",
    name: "High Protein Meal",
    nameTe: "హై ప్రొటీన్ మీల్",
    desc: "Maximum protein density meal combining boiled eggs, grilled chicken or paneer with sprouts salad.",
    cats: ["diet-meals"],
    diet: "nonveg",
    price: 210,
    serving: "1 Meal Box",
    prepTime: "15 min",
    bestTime: "Post-Workout / Lunch",
    kcalBand: "420–460 kcal",
    img: "https://i.pinimg.com/736x/2d/ba/1a/2dba1a4c7d023aea42f0142c0b4cb434.jpg",
    ingredients: ["Grilled Chicken (or Paneer)", "2 Egg Whites", "Sprouts Salad", "Green Veggies"],
    ingredientsTe: "గ్రిల్డ్ చికెన్, ఎగ్ వైట్స్, మొలకల సలాడ్, పచ్చని కూరగాయలు",
    allergens: ["egg"],
    n: { calories: 440, protein: 38, carbs: 24, fat: 12, fibre: 8, sugar: 3, sodium: 460, calcium: 110, iron: 4.2, potassium: 640, vitC: 22 },
    bestFor: ["Gym Workouts", "Muscle Building", "Low Carb Diet"],
    avoidIf: ["Egg Allergy"],
    benefits: ["38g pure protein", "Accelerates muscle recovery", "High thermic effect"],
    popular: true,
  },
  {
    id: "low-carb-meal",
    name: "Low Carb Meal",
    nameTe: "లో కార్బ్ మీల్",
    desc: "Strictly minimal carbohydrates with roasted veggies, grilled protein, and healthy seed toppings.",
    cats: ["diet-meals"],
    diet: "veg",
    price: 180,
    serving: "1 Meal Box",
    prepTime: "12 min",
    bestTime: "Dinner / Lunch",
    kcalBand: "320–360 kcal",
    img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    ingredients: ["Cauliflower Rice / Veggies", "Paneer Cubes", "Spinach", "Flax/Chia Seeds"],
    ingredientsTe: "క్యాలీఫ్లవర్ రైస్, పనీర్ ముక్కలు, పాలకూర, అవిసె గింజలు",
    allergens: ["dairy"],
    n: { calories: 340, protein: 20, carbs: 16, fat: 18, fibre: 9, sugar: 3, sodium: 310, calcium: 260, iron: 3.1, potassium: 510, vitC: 34 },
    bestFor: ["Diabetes Control", "Weight Loss", "PCOS Management"],
    avoidIf: ["Lactose Intolerance"],
    benefits: ["Only 16g carbs", "Stabilizes insulin and blood sugar", "High satiety"],
  },

  // ======================= 5. SALADS =======================
  {
    id: "green-salad",
    name: "Green Salad",
    nameTe: "గ్రీన్ సలాడ్",
    desc: "Fresh and crunchy cucumber, lettuce, bell peppers, tomatoes, and lime mint dressing.",
    cats: ["salads"],
    diet: "vegan",
    price: 80,
    serving: "250 g bowl",
    prepTime: "8 min",
    bestTime: "Anytime / Side",
    kcalBand: "90–120 kcal",
    img: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    ingredients: ["Cucumber", "Lettuce", "Capsicum", "Tomato", "Lemon Dressing"],
    ingredientsTe: "దోసకాయ, లెట్యూస్, క్యాప్సికం, టమాటా, నిమ్మ రసం",
    allergens: [],
    n: { calories: 100, protein: 3, carbs: 16, fat: 1, fibre: 5, sugar: 6, sodium: 120, calcium: 60, iron: 1.2, potassium: 420, vitC: 45 },
    bestFor: ["Light Meal Side", "Detox", "Hydration"],
    avoidIf: [],
    benefits: ["Rich in vitamin C & potassium", "Very low calories", "Hydrates body cells"],
  },
  {
    id: "chicken-salad",
    name: "Chicken Salad",
    nameTe: "చికెన్ సలాడ్",
    desc: "Grilled shredded chicken breast tossed with crisp lettuce, sweet corn, cherry tomatoes, and yogurt-herb dressing.",
    cats: ["salads"],
    diet: "nonveg",
    price: 160,
    serving: "300 g bowl",
    prepTime: "10 min",
    bestTime: "Dinner",
    kcalBand: "260–290 kcal",
    img: "https://i.pinimg.com/1200x/a6/b0/48/a6b0482fe9ccf6121f34450899dbc644.jpg",
    ingredients: ["Grilled Chicken 120g", "Lettuce", "Sweet Corn", "Tomato", "Curd Herb Dressing"],
    ingredientsTe: "గ్రిల్డ్ చికెన్, లెట్యూస్, స్వీట్ కార్న్, టమాటా, పెరుగు డ్రెస్సింగ్",
    allergens: ["dairy"],
    n: { calories: 280, protein: 30, carbs: 15, fat: 8, fibre: 4, sugar: 4, sodium: 380, calcium: 80, iron: 2.1, potassium: 510, vitC: 22 },
    bestFor: ["High Protein Dinner", "Weight Loss Meal Replacement"],
    avoidIf: [],
    benefits: ["30g pure lean protein", "Zero mayo used", "Very filling and light"],
    popular: true,
  },
  {
    id: "fruit-salad",
    name: "Fruit Salad",
    nameTe: "ఫ్రూట్ సలాడ్",
    desc: "Cut fresh daily: papaya, green apple, watermelon, pomegranate, and seasonal fruit bowl.",
    cats: ["salads"],
    diet: "vegan",
    price: 90,
    serving: "250 g bowl",
    prepTime: "5 min",
    bestTime: "Morning / Mid-Morning",
    kcalBand: "130–160 kcal",
    img: "https://i.pinimg.com/1200x/f6/32/f8/f632f8aed551acab34dfc75d6be24cd4.jpg",
    ingredients: ["Papaya", "Apple", "Watermelon", "Pomegranate", "Chia seeds"],
    ingredientsTe: "బొప్పాయి, యాపిల్, పుచ్చకాయ, దానిమ్మ, చియా గింజలు",
    allergens: [],
    n: { calories: 140, protein: 2, carbs: 32, fat: 0.5, fibre: 6, sugar: 24, sodium: 15, calcium: 40, iron: 0.8, potassium: 450, vitC: 60 },
    bestFor: ["Mid-Morning Snack", "Natural Sugar Cravings", "Skin Health"],
    avoidIf: ["Strict Keto"],
    benefits: ["High natural antioxidants", "Enzymes that improve digestion", "No added syrup"],
  },
  {
    id: "sprouts-salad",
    name: "Sprouts Salad",
    nameTe: "మొలకల సలాడ్",
    desc: "Steamed whole moong & chickpea sprouts with finely chopped cucumber, tomato, lemon, and pink salt.",
    cats: ["salads", "snacks"],
    diet: "vegan",
    price: 80,
    serving: "200 g bowl",
    prepTime: "5 min",
    bestTime: "Morning / Evening Snack",
    kcalBand: "140–170 kcal",
    img: "https://i.pinimg.com/1200x/d5/c5/3a/d5c53a3d324681843d40bef636eb217b.jpg",
    ingredients: ["Moong Sprouts", "Chickpea Sprouts", "Cucumber", "Lemon", "Pink Salt"],
    ingredientsTe: "పెసర మొలకలు, శనగ మొలకలు, దోసకాయ, నిమ్మరసం, ఉప్పు",
    allergens: [],
    n: { calories: 150, protein: 10, carbs: 22, fat: 1.5, fibre: 7, sugar: 3, sodium: 140, calcium: 50, iron: 2.8, potassium: 380, vitC: 22 },
    bestFor: ["Plant Protein", "Evening Snack", "Diabetic Friendly"],
    avoidIf: [],
    benefits: ["10g natural plant protein", "7g high fibre", "Boosts metabolic rate"],
    popular: true,
  },

  // ======================= 6. ROTI ITEMS =======================
  {
    id: "roti",
    name: "Roti",
    nameTe: "రోటీ",
    desc: "Traditional 100% whole wheat flatbread made on tawa without oil.",
    cats: ["roti-items"],
    diet: "vegan",
    price: 15,
    serving: "1 pc",
    prepTime: "5 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "75–85 kcal",
    img: "https://i.pinimg.com/1200x/2a/27/09/2a27096c2010304ec371e3ee9371a070.jpg",
    ingredients: ["Whole Wheat Flour", "Water", "Salt"],
    ingredientsTe: "గోధుమ పిండి, నీరు, ఉప్పు",
    allergens: ["gluten"],
    n: { calories: 80, protein: 3, carbs: 16, fat: 0.5, fibre: 2.5, sugar: 0, sodium: 60, calcium: 10, iron: 0.9, potassium: 70, vitC: 0 },
    bestFor: ["Daily Bread", "Weight Loss"],
    avoidIf: ["Gluten Allergy"],
    benefits: ["Zero maida", "Good complex carbohydrates", "Easy to digest"],
  },
  {
    id: "butter-roti",
    name: "Butter Roti",
    nameTe: "బటర్ రోటీ",
    desc: "Soft whole wheat roti topped with a light brush of pure cow butter.",
    cats: ["roti-items"],
    diet: "veg",
    price: 20,
    serving: "1 pc",
    prepTime: "5 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "95–110 kcal",
    img: "https://i.pinimg.com/736x/0f/02/46/0f0246ce19275cd8c6b43b85ae9487a7.jpg",
    ingredients: ["Whole Wheat Flour", "Cow Butter", "Water", "Salt"],
    ingredientsTe: "గోధుమ పిండి, ఆవు వెన్న, నీరు",
    allergens: ["gluten", "dairy"],
    n: { calories: 105, protein: 3, carbs: 16, fat: 3.5, fibre: 2.5, sugar: 0, sodium: 75, calcium: 15, iron: 0.9, potassium: 75, vitC: 0 },
    bestFor: ["Soft Flavourful Roti"],
    avoidIf: ["Gluten Allergy", "Lactose Intolerance"],
    benefits: ["Healthy fats for joint health", "Soft texture", "100% whole wheat"],
  },
  {
    id: "phulka",
    name: "Phulka",
    nameTe: "పుల్కా",
    desc: "Oil-free puffy whole wheat roti roasted directly over flame. Ultra-light.",
    cats: ["roti-items"],
    diet: "vegan",
    price: 15,
    serving: "1 pc",
    prepTime: "5 min",
    bestTime: "Dinner / Lunch",
    kcalBand: "65–75 kcal",
    img: "https://i.pinimg.com/736x/88/60/dd/8860dd83b5216542e7977d4e364c81b3.jpg",
    ingredients: ["Whole Wheat Flour", "Water"],
    ingredientsTe: "గోధుమ పిండి, నీరు",
    allergens: ["gluten"],
    n: { calories: 70, protein: 2.8, carbs: 14, fat: 0.3, fibre: 2.4, sugar: 0, sodium: 40, calcium: 10, iron: 0.8, potassium: 65, vitC: 0 },
    bestFor: ["Strict Weight Loss", "Diabetic Patients"],
    avoidIf: ["Gluten Allergy"],
    benefits: ["Completely zero oil", "Easiest to digest", "Lowest calorie roti"],
    popular: true,
  },
  {
    id: "multi-grain-roti",
    name: "Multi Grain Roti",
    nameTe: "మల్టీ గ్రెయిన్ రోటీ",
    desc: "Power-packed roti made of wheat, ragi, jowar, bajra, and oats flour.",
    cats: ["roti-items"],
    diet: "vegan",
    price: 25,
    serving: "1 pc",
    prepTime: "5 min",
    bestTime: "Lunch / Dinner",
    kcalBand: "85–95 kcal",
    img: "https://i.pinimg.com/736x/e0/0b/92/e00b92b9d7a3852eb2c8323c32b531d0.jpg",
    ingredients: ["Wheat", "Ragi", "Jowar", "Bajra", "Oats"],
    ingredientsTe: "గోధుమ, రాగి, జొన్న, సజ్జ, ఓట్స్ పిండి",
    allergens: ["gluten"],
    n: { calories: 90, protein: 4, carbs: 16, fat: 1, fibre: 4, sugar: 0, sodium: 50, calcium: 35, iron: 1.5, potassium: 110, vitC: 0 },
    bestFor: ["Diabetes Control", "High Fibre Diet", "Cholesterol Management"],
    avoidIf: [],
    benefits: ["4g fibre per roti", "Rich in iron & calcium", "Low glycemic index"],
    popular: true,
  },

  // ======================= 7. SNACKS =======================
  {
    id: "boiled-egg",
    name: "Boiled Egg",
    nameTe: "ఉడికించిన గుడ్డు",
    desc: "Hard-boiled farm eggs seasoned with rock salt and crushed black pepper.",
    cats: ["snacks"],
    diet: "egg",
    price: 35,
    serving: "2 whole eggs",
    prepTime: "5 min",
    bestTime: "Pre/Post-Workout / Snack",
    kcalBand: "140–155 kcal",
    img: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=800&q=80",
    ingredients: ["Eggs (2)", "Black Pepper", "Rock Salt"],
    ingredientsTe: "గుడ్లు (2), మిరియాల పొడి, ఉప్పు",
    allergens: ["egg"],
    n: { calories: 145, protein: 13, carbs: 1, fat: 10, fibre: 0, sugar: 0.5, sodium: 180, calcium: 55, iron: 1.8, potassium: 140, vitC: 0 },
    bestFor: ["Quick Snack", "Pre/Post Workout Protein"],
    avoidIf: ["Egg Allergy"],
    benefits: ["13g high quality protein", "Rich in vitamin B12 & choline", "Instant hunger fix"],
  },
  {
    id: "protein-snack-box",
    name: "Protein Snack Box",
    nameTe: "ప్రొటీన్ స్నాక్ బాక్స్",
    desc: "Balanced snack box with boiled eggs, paneer/tofu cubes, roasted almonds, and cucumber slices.",
    cats: ["snacks"],
    diet: "egg",
    price: 120,
    serving: "1 Box",
    prepTime: "5 min",
    bestTime: "4 PM Snack / Post-Workout",
    kcalBand: "260–300 kcal",
    img: "https://i.pinimg.com/736x/9e/bb/75/9ebb75a61012355ec47fb987a6105f05.jpg",
    ingredients: ["Boiled Egg", "Paneer Cubes", "Roasted Almonds", "Cucumber"],
    ingredientsTe: "ఉడికించిన గుడ్డు, పనీర్ ముక్కలు, బాదం, దోసకాయ",
    allergens: ["egg", "dairy", "nuts"],
    n: { calories: 280, protein: 18, carbs: 10, fat: 18, fibre: 4, sugar: 3, sodium: 220, calcium: 190, iron: 2.2, potassium: 340, vitC: 6 },
    bestFor: ["4 PM Office Snack", "Gym Athletes"],
    avoidIf: ["Nut Allergy", "Egg Allergy"],
    benefits: ["18g mixed proteins", "Healthy fats from nuts", "Zero junk replacement"],
    popular: true,
  },
  {
    id: "sprouts-chaat",
    name: "Sprouts Chaat",
    nameTe: "మొలకల చాట్",
    desc: "Zesty steamed moong sprouts tossed with onions, tomatoes, coriander, lemon, and chaat spices.",
    cats: ["snacks"],
    diet: "vegan",
    price: 79,
    serving: "180 g cup",
    prepTime: "5 min",
    bestTime: "Evening Snack",
    kcalBand: "150–180 kcal",
    img: "https://i.pinimg.com/736x/56/07/b8/5607b8d5a602203f983065cc1cae68c4.jpg",
    ingredients: ["Moong Sprouts", "Onion", "Tomato", "Lemon", "Chaat Masala"],
    ingredientsTe: "పెసర మొలకలు, ఉల్లి, టమాటా, నిమ్మ, చాట్ మసాలా",
    allergens: [],
    n: { calories: 165, protein: 10, carbs: 24, fat: 3, fibre: 7, sugar: 4, sodium: 260, calcium: 55, iron: 2.6, potassium: 400, vitC: 24 },
    bestFor: ["Weight Loss", "Evening Snack", "Diabetic Friendly"],
    avoidIf: [],
    benefits: ["Kills junk food cravings", "10g plant protein", "Very high in fibre"],
    popular: true,
  },

  // ======================= 9. HEALTHY SMOOTHIES =======================
  {
    id: "banana-smoothie",
    name: "Banana Smoothie",
    nameTe: "బనానా స్మూతీ",
    desc: "Fresh banana blended with cold milk, rolled oats, and chia seeds. Natural energy boost.",
    cats: ["smoothies"],
    diet: "veg",
    price: 90,
    serving: "300 ml",
    prepTime: "5 min",
    bestTime: "Morning / Pre-Workout",
    kcalBand: "220–250 kcal",
    img: "https://i.pinimg.com/1200x/e7/b9/ba/e7b9bab4908904dd1be045dd1338d77c.jpg",
    ingredients: ["Banana", "Milk", "Rolled Oats", "Chia Seeds"],
    ingredientsTe: "అరటిపండు, పాలు, ఓట్స్, చియా గింజలు",
    allergens: ["dairy"],
    n: { calories: 235, protein: 7, carbs: 42, fat: 4, fibre: 5, sugar: 20, sodium: 75, calcium: 180, iron: 1.2, potassium: 540, vitC: 10 },
    bestFor: ["Pre-Workout Energy", "Morning Breakfast Shake"],
    avoidIf: ["Lactose Intolerance"],
    benefits: ["Rich in potassium", "Instant healthy carbohydrates", "No artificial sugar"],
  },
  {
    id: "mango-smoothie",
    name: "Mango Smoothie",
    nameTe: "మ్యాంగో స్మూతీ",
    desc: "Juicy ripe mango pulp blended with chilled low-fat milk and a hint of cardamom.",
    cats: ["smoothies"],
    diet: "veg",
    price: 110,
    serving: "300 ml",
    prepTime: "5 min",
    bestTime: "Mid-Day / Refreshment",
    kcalBand: "210–240 kcal",
    img: "https://i.pinimg.com/736x/41/5b/04/415b04690d8f2c91a0937158e2cb3624.jpg",
    ingredients: ["Ripe Mango", "Milk", "Cardamom"],
    ingredientsTe: "మామిడి పండు, పాలు, ఏలకులు",
    allergens: ["dairy"],
    n: { calories: 225, protein: 6, carbs: 44, fat: 3, fibre: 3, sugar: 32, sodium: 65, calcium: 160, iron: 0.8, potassium: 410, vitC: 40 },
    bestFor: ["Summer Refreshment", "Energy"],
    avoidIf: ["Lactose Intolerance", "Strict Diabetes"],
    benefits: ["Rich in Vitamin A & C", "No artificial puree", "Luscious natural taste"],
  },
  {
    id: "chocolate-smoothie",
    name: "Chocolate Smoothie",
    nameTe: "చాక్లెట్ స్మూతీ",
    desc: "Unsweetened pure cocoa blended with milk, banana, and peanut butter for a healthy dessert feel.",
    cats: ["smoothies"],
    diet: "veg",
    price: 120,
    serving: "300 ml",
    prepTime: "5 min",
    bestTime: "Post-Workout",
    kcalBand: "260–290 kcal",
    img: "https://i.pinimg.com/1200x/46/af/91/46af91f517e96fbc0bb26cddc16903d4.jpg",
    ingredients: ["Raw Cocoa Powder", "Milk", "Banana", "Peanut Butter"],
    ingredientsTe: "కోకో పౌడర్, పాలు, అరటిపండు, పీనట్ బటర్",
    allergens: ["dairy", "nuts"],
    n: { calories: 275, protein: 11, carbs: 36, fat: 9, fibre: 5, sugar: 18, sodium: 110, calcium: 200, iron: 2.2, potassium: 560, vitC: 6 },
    bestFor: ["Chocolate Cravings", "Post-Workout Recovery"],
    avoidIf: ["Nut Allergy", "Lactose Intolerance"],
    benefits: ["Rich in flavonoids & magnesium", "11g natural protein", "Healthy guilt-free chocolate"],
    popular: true,
  },
  {
    id: "dates-smoothie",
    name: "Dates Smoothie",
    nameTe: "ఖర్జూర స్మూతీ",
    desc: "Natural sweet Arabian dates blended with chilled milk and almonds for iron-rich energy.",
    cats: ["smoothies"],
    diet: "veg",
    price: 110,
    serving: "300 ml",
    prepTime: "5 min",
    bestTime: "Morning / Pre-Workout",
    kcalBand: "250–280 kcal",
    img: "https://i.pinimg.com/736x/31/85/38/318538bbf89f7e5361d8eb6c7743df2b.jpg",
    ingredients: ["Arabian Dates", "Milk", "Almonds"],
    ingredientsTe: "ఖర్జూరాలు, పాలు, బాదం",
    allergens: ["dairy", "nuts"],
    n: { calories: 265, protein: 7, carbs: 48, fat: 5, fibre: 5, sugar: 36, sodium: 75, calcium: 210, iron: 2.4, potassium: 590, vitC: 2 },
    bestFor: ["Anaemia / Low Iron", "Stamina Boost"],
    avoidIf: ["Diabetes (high natural sugar)", "Nut Allergy"],
    benefits: ["Natural iron & magnesium source", "Zero refined sugars", "Instant stamina"],
  },

  // ======================= 10. FRESH JUICES =======================
  {
    id: "watermelon-juice",
    name: "Watermelon Juice",
    nameTe: "పుచ్చకాయ జ్యూస్",
    desc: "100% freshly pressed watermelon with fresh mint and lemon. Hydrating summer cooler.",
    cats: ["fresh-juices"],
    diet: "vegan",
    price: 60,
    serving: "250 ml",
    prepTime: "5 min",
    bestTime: "Morning / Summer Afternoon",
    kcalBand: "70–90 kcal",
    img: "https://i.pinimg.com/736x/18/e7/da/18e7da068367328100f4e7812aa840e7.jpg",
    ingredients: ["Watermelon", "Lemon", "Mint"],
    ingredientsTe: "పుచ్చకాయ, నిమ్మ, పుదీనా",
    allergens: [],
    n: { calories: 80, protein: 1.5, carbs: 19, fat: 0, fibre: 1, sugar: 16, sodium: 5, calcium: 20, iron: 0.5, potassium: 320, vitC: 20 },
    bestFor: ["Hydration", "Low-Calorie Thirst Quencher"],
    avoidIf: [],
    benefits: ["92% water content", "Rich in lycopene & electrolytes", "No water or sugar added"],
    popular: true,
  },
  {
    id: "orange-juice",
    name: "Orange Juice",
    nameTe: "ఆరెంజ్ జ్యూస్",
    desc: "Fresh cold-pressed sweet oranges packed with natural immunity-boosting Vitamin C.",
    cats: ["fresh-juices"],
    diet: "vegan",
    price: 80,
    serving: "250 ml",
    prepTime: "5 min",
    bestTime: "Morning Breakfast",
    kcalBand: "100–120 kcal",
    img: "https://i.pinimg.com/736x/b0/7a/8d/b07a8da05c4ff42119ae0a2ae0aef279.jpg",
    ingredients: ["Fresh Oranges"],
    ingredientsTe: "తాజా నారింజ పండ్లు",
    allergens: [],
    n: { calories: 110, protein: 2, carbs: 26, fat: 0, fibre: 1.5, sugar: 21, sodium: 5, calcium: 30, iron: 0.4, potassium: 450, vitC: 120 },
    bestFor: ["Immunity", "Skin Radiance", "Iron Absorption"],
    avoidIf: ["Acidity"],
    benefits: ["Over 100% daily Vitamin C requirement", "Pure raw juice", "Zero preservatives"],
  },
  {
    id: "pineapple-juice",
    name: "Pineapple Juice",
    nameTe: "పైనాపిల్ జ్యూస్",
    desc: "Tangy sweet pineapple juice rich in bromelain enzymes that promote smooth digestion.",
    cats: ["fresh-juices"],
    diet: "vegan",
    price: 80,
    serving: "250 ml",
    prepTime: "5 min",
    bestTime: "Post-Meal / Afternoon",
    kcalBand: "110–130 kcal",
    img: "https://i.pinimg.com/736x/a1/f6/b5/a1f6b5b9c6152fcf586461c483ec2dfa.jpg",
    ingredients: ["Fresh Pineapple", "Mint"],
    ingredientsTe: "అనాస పండు, పుదీనా",
    allergens: [],
    n: { calories: 120, protein: 1, carbs: 29, fat: 0, fibre: 2, sugar: 24, sodium: 5, calcium: 25, iron: 0.6, potassium: 310, vitC: 70 },
    bestFor: ["Digestion", "Anti-Inflammatory"],
    avoidIf: ["Severe Acidity"],
    benefits: ["Contains bromelain digestive enzyme", "Reduces joint inflammation", "Fresh & cooling"],
  },
  {
    id: "carrot-juice",
    name: "Carrot Juice",
    nameTe: "క్యారెట్ జ్యూస్",
    desc: "Cold-pressed sweet carrots with a touch of ginger for eye health and glowing skin.",
    cats: ["fresh-juices"],
    diet: "vegan",
    price: 80,
    serving: "250 ml",
    prepTime: "5 min",
    bestTime: "Early Morning",
    kcalBand: "85–105 kcal",
    img: "https://i.pinimg.com/736x/5e/35/bb/5e35bb6cde159364b352f3eb098f1bb1.jpg",
    ingredients: ["Red Carrots", "Ginger", "Lemon"],
    ingredientsTe: "క్యారెట్లు, అల్లం, నిమ్మ",
    allergens: [],
    n: { calories: 95, protein: 2, carbs: 21, fat: 0.3, fibre: 3, sugar: 12, sodium: 70, calcium: 45, iron: 1.1, potassium: 490, vitC: 15 },
    bestFor: ["Eye Health", "Skin Glow", "Beta-Carotene"],
    avoidIf: [],
    benefits: ["High Vitamin A & Beta-carotene", "Supports liver detox", "No added sugar"],
  },
];

export const getProduct = (id: string) => PRODUCTS.find((p) => p.id === id);

export const byCategory = (k: CatKey) =>
  k === "all" ? PRODUCTS : PRODUCTS.filter((p) => p.cats.includes(k));

export const DIET_LABEL: Record<Diet, string> = {
  veg: "Veg",
  vegan: "Vegan",
  egg: "Egg",
  nonveg: "Non-Veg",
};

export const ALLERGENS = ["dairy", "nuts", "egg", "gluten", "seafood"] as const;

export const ALLERGEN_LABEL: Record<string, string> = {
  dairy: "Dairy",
  nuts: "Nuts",
  egg: "Egg",
  gluten: "Gluten",
  seafood: "Seafood",
};